Starting to publish manylinux wagons and 1.5 DSL YAML

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -40,17 +40,44 @@ executors:
       image: ubuntu-2004:202201-02
 
 commands:
+
+
+  setup_manager:
+    steps:
+      - run: |
+          if [[ -z "${CLOUDIFY_HOST}" ]]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TENANT}" ]] && [ -z "${CIRCLE_PROJECT_REPONAME}" ]; then
+              exit 1
+          fi
+      - run: |
+          if [[ -z "${CLOUDIFY_TOKEN}" ]]; then
+              exit 1
+          fi
+      - run: |
+          response=$(curl --write-out '%{http_code}' --silent --insecure --header "Tenant: ${CLOUDIFY_TENANT}" --header "Authentication-Token: ${CLOUDIFY_TOKEN}" https://$CLOUDIFY_HOST/api/v3.1/status --output /dev/null)
+          if [[ $response != 200 ]]; then
+              echo "Failed to get manager status";
+              exit 1
+          fi
+      - run: pip3 install urllib3==1.26.15 requests-toolbelt==0.10.1
+      - run: pip3 install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/refs/heads/master.zip
+      - run: git submodule update --init --recursive --remote
+
   prepare_test_manager:
     steps:
       - run: ls -alR
-      - run: ecosystem-test prepare-test-manager -l $TEST_LICENSE -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key -es spot_account=$spot_account -es spot_token=$spot_token --yum-package python-netaddr --yum-package git -p $(find ~/project/workspace/build/ -name *centos-Core*x86_64.wgn)  ~/project/plugin.yaml
-      - run: ecosystem-test upload-plugin -PN aws
-      - run: ecosystem-test upload-plugin -PN terraform
-      - run: ecosystem-test upload-plugin -PN utilities
-
+      - run: ecosystem-test prepare-remote-test-manager -es aws_access_key_id=$aws_access_key_id -es aws_secret_access_key=$aws_secret_access_key -es spot_account=$spot_account -es spot_token=$spot_token -p $(find ~/project/workspace/build/ -name *manylinux-py311-none-linux_x86_64.wgn)  ~/project/plugin_1_5.yaml
+      - run: ecosystem-test remote-upload-plugin -PN aws --wagon-type manylinux
+      - run: ecosystem-test remote-upload-plugin -PN terraform --wagon-type manylinux
+      - run: ecosystem-test remote-upload-plugin -PN helm --wagon-type manylinux
+      - run: ecosystem-test remote-upload-plugin -PN utilities --wagon-type manylinux
+      - run: ecosystem-test remote-upload-plugin -PN kubernetes --wagon-type manylinux
   run_eks_test:
     steps:
-      - run: ecosystem-test local-blueprint-test -b examples/blueprint.yaml --test-id=spot-ocean-eks -i aws_region_name=me-central-1 -i eks_cluster_name=test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000
+      - run: ecosystem-test remote-blueprint-test -b examples/blueprint.yaml --test-id=spot-ocean-eks -i aws_region_name=me-central-1 -i eks_cluster_name=test-$CIRCLE_BUILD_NUM --on-failure=uninstall-force --timeout=3000
 jobs:
 
   cf_integration_tests_py3:
@@ -61,20 +88,9 @@ jobs:
       - checkout
       - attach_workspace:
           at: workspace
-      - managerorb/create_manager_container_latest
+      - setup_manager
       - prepare_test_manager
       - run_eks_test
-
-  autoscaleing_integration_tests_py3:
-    executor: cloudify-machine-py3
-    environment:
-      CLOUDIFY_SSL_TRUST_ALL: true
-    steps:
-      - checkout
-      - attach_workspace:
-          at: workspace
-      - managerorb/create_manager_container_latest
-      - prepare_test_manager
 
 workflows:
   version: 2
@@ -99,11 +115,13 @@ workflows:
           filters:
             branches:
               only: /([0-9\.]*\-build|main|dev)/
+      - wagonorb/wagon_311:
+          filters:
+            branches:
+              only: /([0-9\.]*\-build|master|dev)/
       - cf_integration_tests_py3:
           requires:
-            - wagonorb/wagon
-            - wagonorb/rhel_wagon
-            - wagonorb/arch64_wagon
+            - wagonorb/wagon_311
           filters:
             branches:
               only: /([0-9\.]*\-build|main|dev)/
@@ -113,6 +131,7 @@ workflows:
               only: /main/
           requires:
             - node/unittests_job
+            - wagonorb/wagon_311
             - wagonorb/rhel_wagon
             - wagonorb/wagon
             - wagonorb/arch64_wagon
@@ -142,26 +161,16 @@ workflows:
             - slack-secrets
           <<: *unittest-post-steps
       - node/validate_version_job
-      - wagonorb/rhel_wagon:
+      - wagonorb/wagon_311:
           filters:
             branches:
-              only: /([0-9\.]*\-build|main|dev)/
-      - wagonorb/wagon:
-          filters:
-            branches:
-              only: /([0-9\.]*\-build|main|dev)/
-      - wagonorb/arch64_wagon:
-          filters:
-            branches:
-              only: /([0-9\.]*\-build|main|dev)/
+              only: /([0-9\.]*\-build|master|dev)/
       - cf_integration_tests_py3:
           context: 
             - slack-secrets
           <<: *job-post-steps
           requires:
-            - wagonorb/wagon
-            - wagonorb/rhel_wagon
-            - wagonorb/arch64_wagon
+            - wagonorb/wagon_311
           filters:
             branches:
               only: /([0-9\.]*\-build|main|dev)/
